# Generated by Django 4.0.3 on 2022-03-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ownerId',
            field=models.IntegerField(default=0),
        ),
    ]
